final:
	#Part A
	g++ project1_parta.cpp fibonnaci.cpp -o fibPartA
	echo "---Part A Driver---" > project1_parta.txt
	cat project1_parta.cpp >> project1_parta.txt
	echo "\n" >> project1_parta.txt
	echo "---Fibonnaci Header---" >> project1_parta.txt
	echo "\n" >> project1_parta.txt
	cat fibonnaci.h >> project1_parta.txt
	echo "\n" >> project1_parta.txt
	echo "---Fibonnaci Implementation---" >> project1_parta.txt
	cat fibonnaci.cpp >> project1_parta.txt
	echo "\n" >> project1_parta.txt
	echo "---Part A Output---" >> project1_parta.txt
	echo "\n" >> project1_parta.txt
	./fibPartA 20 >> project1_parta.txt
	cat project1_parta.txt

	#Part B
	g++ project1_partb.cpp fibonnaci.cpp -o fibPartB
	echo "---Part B Driver---" > project1_partb.txt
	cat project1_partb.cpp >> project1_partb.txt
	echo "\n" >> project1_partb.txt
	echo "---Fibonnaci Header---" >> project1_partb.txt
	echo "\n" >> project1_partb.txt
	cat fibonnaci.h >> project1_partb.txt
	echo "\n" >> project1_partb.txt
	echo "---Fibonnaci Implementation---" >> project1_partb.txt
	cat fibonnaci.cpp >> project1_partb.txt
	echo "\n" >> project1_partb.txt
	echo "---Part B Output---" >> project1_partb.txt
	echo "\n" >> project1_partb.txt
	./fibPartB 20 >> project1_partb.txt
	cat project1_partb.txt

	#Part C
	g++ project1_partc.cpp fibonnaci.cpp -o fibPartC
	echo "---Part A Driver---" > project1_partc.txt
	cat project1_partc.cpp >> project1_partc.txt
	echo "\n" >> project1_partc.txt
	echo "---Fibonnaci Header---" >> project1_partc.txt
	echo "\n" >> project1_partc.txt
	cat fibonnaci.h >> project1_partc.txt
	echo "\n" >> project1_partc.txt
	echo "---Fibonnaci Implementation---" >> project1_partc.txt
	cat fibonnaci.cpp >> project1_partc.txt
	echo "\n" >> project1_partc.txt
	echo "---Part B Output---" >> project1_partc.txt
	echo "\n" >> project1_partc.txt
	./fibPartC 20 >> project1_partc.txt
	cat project1_partc.txt
partA:
	g++ project1_parta.cpp fibonnaci.cpp -o fibPartA
	./fibPartA 15

partB:
	g++ project1_partb.cpp fibonnaci.cpp -o fibPartB
	./fibPartB 15
	
partC:
	g++ project1_partc.cpp fibonnaci.cpp -o fibPartC
	./fibPartC 15

partD:
	g++ project1_partd.cpp fibonnaci.cpp -o fibPartD
	./fibPartD 15