final:
	#Part A
	g++ project1_parta.cpp fibonnaci.cpp -o fibPartA
	echo "---Part A Driver---" > JANP1A.txt
	cat project1_parta.cpp >> JANP1A.txt
	echo "\n" >> JANP1A.txt
	echo "---Fibonnaci Header---" >> JANP1A.txt
	echo "\n" >> JANP1A.txt
	cat fibonnaci.h >> JANP1A.txt
	echo "\n" >> JANP1A.txt
	echo "---Fibonnaci Implementation---" >> JANP1A.txt
	cat fibonnaci.cpp >> JANP1A.txt
	echo "\n" >> JANP1A.txt
	echo "---Part A Output---" >> JANP1A.txt
	echo "\n" >> JANP1A.txt
	./fibPartA 20 >> JANP1A.txt
	cat JANP1A.txt

	#Part B
	g++ project1_partb.cpp fibonnaci.cpp -o fibPartB
	echo "---Part B Driver---" > JANP1B.txt
	cat project1_partb.cpp >> JANP1B.txt
	echo "\n" >> JANP1B.txt
	echo "---Fibonnaci Header---" >> JANP1B.txt
	echo "\n" >> JANP1B.txt
	cat fibonnaci.h >> JANP1B.txt
	echo "\n" >> JANP1B.txt
	echo "---Fibonnaci Implementation---" >> JANP1B.txt
	cat fibonnaci.cpp >> JANP1B.txt
	echo "\n" >> JANP1B.txt
	echo "---Part B Output---" >> JANP1B.txt
	echo "\n" >> JANP1B.txt
	./fibPartB 20 >> JANP1B.txt
	cat JANP1B.txt

	#Part C
	g++ project1_partc.cpp fibonnaci.cpp -o fibPartC
	echo "---Part C Driver---" > JANP1C.txt
	cat project1_partc.cpp >> JANP1C.txt
	echo "\n" >> JANP1C.txt
	echo "---Fibonnaci Header---" >> JANP1C.txt
	echo "\n" >> JANP1C.txt
	cat fibonnaci.h >> JANP1C.txt
	echo "\n" >> JANP1C.txt
	echo "---Fibonnaci Implementation---" >> JANP1C.txt
	cat fibonnaci.cpp >> JANP1C.txt
	echo "\n" >> JANP1C.txt
	echo "---Part C Output---" >> JANP1C.txt
	echo "\n" >> JANP1C.txt
	./fibPartC 5 >> JANP1C.txt
	./fibPartC 10 >> JANP1C.txt
	./fibPartC 20 >> JANP1C.txt
	./fibPartC 40 >> JANP1C.txt
	./fibPartC 45 >> JANP1C.txt
	cat JANP1C.txt

	#Part D
	echo "---Part D Program---" > JANP1D.txt
	cat project1_partd.py >> JANP1D.txt
	echo "\n" >> JANP1D.txt
	echo "---Part D Output---" >> JANP1D.txt
	echo "\n" >> JANP1D.txt
	python project1_partd.py >> JANP1D.txt
	cat JANP1D.txt

partA:
	g++ project1_parta.cpp fibonnaci.cpp -o fibPartA
	./fibPartA 15

partB:
	g++ project1_partb.cpp fibonnaci.cpp -o fibPartB
	./fibPartB 15
	
partC:
	g++ project1_partc.cpp fibonnaci.cpp -o fibPartC
	./fibPartC 15

partD:
	g++ project1_partd.cpp fibonnaci.cpp -o fibPartD
	./fibPartD 15